export const UPDATE_SEARCH_CONTENT = 'UPDATE_SEARCH_CONTENT';
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONGS';
export const FAIL_RECEIVE_SONGS = 'FAIL_RECEIVE_SONGS';
export const UPDATE_CURRENT_TRACK = 'UPDATE_CURRENT_TRACK';
export const PLAY = 'PLAY';
export const PAUSE = 'PAUSE';
